import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/provider";
import { ToastContainer } from "react-toastify";
import { Suspense } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Optional: Use as a CSS variable
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className={inter.variable}>
      <body className="bg-bgGrey">
        <Suspense fallback={<div>Loading...</div>}>
          <ReduxProvider>{children}</ReduxProvider>
        </Suspense>
      </body>
    </html>
  );
}
