import { Geist, Geist_Mono, Inter } from "next/font/google";
import "../globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import ThemeProvider from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import logo from "../../../public/assets/Logo.png";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <SidebarProvider>
        <AppSidebar logo={logo} />
        <div className=" w-full">
          <Header ModeToggle={ModeToggle} SidebarTrigger={SidebarTrigger} />
          {children}
        </div>
      </SidebarProvider>
    </ThemeProvider>
  );
}
